# Site settings
title: Andrew Shuttleworth
email: ashuttleworth@gmail.com
description: "I work with Made Media. We make websites for arts organizations."
baseurl: ""
url: "http://ashuttleworth.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 5
paginate_path: page:num
gems: [jekyll-paginate]