# Site settings
title: Andrew Shuttleworth
email: andrew@shuttleworth.is
description: "I work for Lincoln Center in New York."
baseurl: ""
url: "http://ashuttleworth.com"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
