# Site settings
title: Andrew Shuttleworth
email: andrew@shuttleworth.is
description: "I work for Lincoln Center in New York."
baseurl: ""
url: "http://ashuttleworth.com"

# Build settings
# markdown: maruku
permalink: /:year/:month/:title
paginate: 5
paginate_path: page:num